# Generated by Django 2.0.5 on 2021-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_model',
                'managed': True,
            },
        ),
    ]
